# Lecture 5 (Binomial Test) {#binomial_test}

## Lecture

Only one part of this lecture covers the binomial test. The other part covers factor analysis with Emma Mills. The lecture recording is available [here](https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=e47787f9-26da-4553-964f-ae360179eb0a). The slides are available [here](https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785884).

## Pre-lab work

There is no lab associated with this content.

## Lab

There is no lab associated with this content.

## Independent learning 

This is optional, but recommended. The answers are found below.

### Activity 1

**One sample-test or binomial test?**

Disclaimer: All data are made up (and these estimates may be utterly ridiculous!)

The answers are in the next section.

For the following examples, write down whether you think the test conducted should be a one-sample t-test or a binomial test. 

1. You are the coach of a football team. You are interested in whether the running distance of your players significantly differs from the England national football team. You know, on average, England football players run 10km per game. 

2. You are the coach of a football team. You are interested in whether the proportion of games your team scores a goal is significantly different from that of the England national team. You know that on average, the England national team scores a goal in 60% of games. 

3. You are a university lecturer. You decide to introduce post-lecture worksheets to help students to consolidate knowledge learned during lectures. You are interested in whether the proportion of students passing the class test differs between this year and last year. You don’t have individual marks for last year’s students, but you do know that 74% of the last year’s cohort passed the class test. 

4. You are a university lecturer. You decide to introduce post-lecture worksheets to help students to consolidate knowledge learned during lectures. You are interested in whether the score on the class test differs between this year and last year. You know that last year, the average mark on the class test was 62% (or 0.62 expressed a proportion).

5. You are a neonatal doctor (a doctor who specialising in caring for newborn babies). You think that babies born in your hospital are quite small. You are interested in whether the proportion of babies who are classed as “small for gestational age” differs between your hospital and the UK average (10%). 

6. You are a neonatal doctor (a doctor who specialising in caring for newborn babies). You think that babies that are born in your hospital are quite small. You are interested in whether the average weight of babies born at your hospital is significantly less than the UK average (3350g). 


### Activity 2

**Identifying “success”**

1. You are a lecturer interested in whether the proportion of students passing your module differs from your colleague’s module. 82% of students (or 0.82 expressed as a proportion) pass your colleague’s module.

2. You are the headteacher of a grammar school which has an entrance exam. You are interested in whether the proportion of children failing the test differs significantly from last year. The failure rate last year was 24% (or 0.24 expressed as a proportion). 

3. You are a teacher. You are interested in whether the proportion of students in your class with special educational needs and disabilities (SEND) significantly differs from the year group average (27%, or 0.27 expressed as a proportion). 

4. You have developed a new flu vaccine. You are interested in whether the proportion of people who develop side effects after your vaccine differs from the flu vaccine currently used by the NHS (37%, or 0.37 expressed as a proportion).  

### Activity 1: Answers

1. One-sample t-test. The value for each individual is continuous.You are interested in whether the mean number of km runs differs from a known value. 

2. Binomial test. Two possible outcomes: team scores or team does not score). You are interested in whether the proportion that a given outcome occurs (i.e. your team scores a goal) differs from a known value. 

3. Binomial test. Two possible outcomes: Each student’s outcome is either “passed class test” or “failed class test”. You are interested in whether the proportion that a given outcome occurs (i.e. passes the class test) differs from a known value.

4. One-sample t-test. The value for each individual is continuous. You are interested in whether the mean score students get differs from a known value.

5. Binomial test. Two possible outcomes: Each baby’s outcome is either “small for gestational age” or “not small for gestational age”. You are interested in whether the proportion that a given outcome occurs (i.e. small for gestational age) differs from a known value.

6. One-sample t-test. The value for each individual is continuous. You are interested in whether the mean weight of babies at your hospital differs from a known value.

Take-home message: A one sample t-test is used when you are interested in comparing the mean of a sample to a known value. The binomial test is used when you are interested in comparing a sample’s proportion of “successes” to a known value.

### Activity 2: Answers

1. Success: pass the module. 
   Failure: fail the module.

2. Success: failing the test.
   Failure: passing the test.
   
3. Success: Has special educational needs.
   Failure: Does not have special educational needs.
   
4. Success: Has side effects.
   Failure: Does not have side effects.
   
Take home message: Success refers to the outcome you are interested in. Sometimes this might be counterintuitive to how we typically think about ‘success’. 
