<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Lecture 6 (Non-parametric tests: Wilcoxon rank-sum and Wilcoxon signed-rank tests) | PSYC234 (Weeks 15-19)</title>
  <meta name="description" content="This contains all of the important documents for Dr Amy Atkinson’s part of PSYC234 (Lectures 5-9)" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Lecture 6 (Non-parametric tests: Wilcoxon rank-sum and Wilcoxon signed-rank tests) | PSYC234 (Weeks 15-19)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This contains all of the important documents for Dr Amy Atkinson’s part of PSYC234 (Lectures 5-9)" />
  <meta name="github-repo" content="amy-atkinson/PSYC234_Part2" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Lecture 6 (Non-parametric tests: Wilcoxon rank-sum and Wilcoxon signed-rank tests) | PSYC234 (Weeks 15-19)" />
  
  <meta name="twitter:description" content="This contains all of the important documents for Dr Amy Atkinson’s part of PSYC234 (Lectures 5-9)" />
  

<meta name="author" content="Amy Atkinson" />


<meta name="date" content="2022-05-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="binomial_test.html"/>
<link rel="next" href="kruskal-friedman.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="binomial_test.html"><a href="binomial_test.html"><i class="fa fa-check"></i><b>2</b> Lecture 5 (Binomial Test)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="binomial_test.html"><a href="binomial_test.html#lecture"><i class="fa fa-check"></i><b>2.1</b> Lecture</a></li>
<li class="chapter" data-level="2.2" data-path="binomial_test.html"><a href="binomial_test.html#pre-lab-work"><i class="fa fa-check"></i><b>2.2</b> Pre-lab work</a></li>
<li class="chapter" data-level="2.3" data-path="binomial_test.html"><a href="binomial_test.html#lab"><i class="fa fa-check"></i><b>2.3</b> Lab</a></li>
<li class="chapter" data-level="2.4" data-path="binomial_test.html"><a href="binomial_test.html#independent-learning"><i class="fa fa-check"></i><b>2.4</b> Independent learning</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="binomial_test.html"><a href="binomial_test.html#activity-1"><i class="fa fa-check"></i><b>2.4.1</b> Activity 1</a></li>
<li class="chapter" data-level="2.4.2" data-path="binomial_test.html"><a href="binomial_test.html#activity-2"><i class="fa fa-check"></i><b>2.4.2</b> Activity 2</a></li>
<li class="chapter" data-level="2.4.3" data-path="binomial_test.html"><a href="binomial_test.html#activity-1-answers"><i class="fa fa-check"></i><b>2.4.3</b> Activity 1: Answers</a></li>
<li class="chapter" data-level="2.4.4" data-path="binomial_test.html"><a href="binomial_test.html#activity-2-answers"><i class="fa fa-check"></i><b>2.4.4</b> Activity 2: Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html"><i class="fa fa-check"></i><b>3</b> Lecture 6 (Non-parametric tests: Wilcoxon rank-sum and Wilcoxon signed-rank tests)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#lecture-1"><i class="fa fa-check"></i><b>3.1</b> Lecture</a></li>
<li class="chapter" data-level="3.2" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#pre-lab-work-1"><i class="fa fa-check"></i><b>3.2</b> Pre-lab work</a></li>
<li class="chapter" data-level="3.3" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#lab-1"><i class="fa fa-check"></i><b>3.3</b> Lab</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#model-script"><i class="fa fa-check"></i><b>3.3.1</b> Model script</a></li>
<li class="chapter" data-level="3.3.2" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#feedback-on-scripts"><i class="fa fa-check"></i><b>3.3.2</b> Feedback on scripts</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#independent-learning-1"><i class="fa fa-check"></i><b>3.4</b> Independent learning</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#activity-1-1"><i class="fa fa-check"></i><b>3.4.1</b> Activity 1</a></li>
<li class="chapter" data-level="3.4.2" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#activity-2-1"><i class="fa fa-check"></i><b>3.4.2</b> Activity 2</a></li>
<li class="chapter" data-level="3.4.3" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#activity-1-answers-1"><i class="fa fa-check"></i><b>3.4.3</b> Activity 1: Answers</a></li>
<li class="chapter" data-level="3.4.4" data-path="wilcoxon-rank-sum-signed-rank.html"><a href="wilcoxon-rank-sum-signed-rank.html#activity-2-answers-1"><i class="fa fa-check"></i><b>3.4.4</b> Activity 2: Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html"><i class="fa fa-check"></i><b>4</b> Lecture 7 (Non-parametric tests: Kruskal-Wallis test and Friedman’s ANOVA)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#lecture-2"><i class="fa fa-check"></i><b>4.1</b> Lecture</a></li>
<li class="chapter" data-level="4.2" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#pre-lab-work-2"><i class="fa fa-check"></i><b>4.2</b> Pre-lab work</a></li>
<li class="chapter" data-level="4.3" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#lab-2"><i class="fa fa-check"></i><b>4.3</b> Lab</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#model-script-1"><i class="fa fa-check"></i><b>4.3.1</b> Model script</a></li>
<li class="chapter" data-level="4.3.2" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#feedback-on-scripts-1"><i class="fa fa-check"></i><b>4.3.2</b> Feedback on scripts</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#independent-learning-2"><i class="fa fa-check"></i><b>4.4</b> Independent learning</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#activity-1-2"><i class="fa fa-check"></i><b>4.4.1</b> Activity 1</a></li>
<li class="chapter" data-level="4.4.2" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#activity-2-2"><i class="fa fa-check"></i><b>4.4.2</b> Activity 2</a></li>
<li class="chapter" data-level="4.4.3" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#activity-1-answers-2"><i class="fa fa-check"></i><b>4.4.3</b> Activity 1: Answers</a></li>
<li class="chapter" data-level="4.4.4" data-path="kruskal-friedman.html"><a href="kruskal-friedman.html#activity-2-answers-2"><i class="fa fa-check"></i><b>4.4.4</b> Activity 2: Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="binary-log-regression.html"><a href="binary-log-regression.html"><i class="fa fa-check"></i><b>5</b> Lecture 8 (Binary logistic regression)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="binary-log-regression.html"><a href="binary-log-regression.html#lecture-3"><i class="fa fa-check"></i><b>5.1</b> Lecture</a></li>
<li class="chapter" data-level="5.2" data-path="binary-log-regression.html"><a href="binary-log-regression.html#pre-lab-work-3"><i class="fa fa-check"></i><b>5.2</b> Pre-lab work</a></li>
<li class="chapter" data-level="5.3" data-path="binary-log-regression.html"><a href="binary-log-regression.html#lab-3"><i class="fa fa-check"></i><b>5.3</b> Lab</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="binary-log-regression.html"><a href="binary-log-regression.html#model-script-2"><i class="fa fa-check"></i><b>5.3.1</b> Model script</a></li>
<li class="chapter" data-level="5.3.2" data-path="binary-log-regression.html"><a href="binary-log-regression.html#feedback-on-scripts-2"><i class="fa fa-check"></i><b>5.3.2</b> Feedback on scripts</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="binary-log-regression.html"><a href="binary-log-regression.html#independent-learning-3"><i class="fa fa-check"></i><b>5.4</b> Independent learning</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="binary-log-regression.html"><a href="binary-log-regression.html#activity-1-3"><i class="fa fa-check"></i><b>5.4.1</b> Activity 1</a></li>
<li class="chapter" data-level="5.4.2" data-path="binary-log-regression.html"><a href="binary-log-regression.html#activity-2-3"><i class="fa fa-check"></i><b>5.4.2</b> Activity 2</a></li>
<li class="chapter" data-level="5.4.3" data-path="binary-log-regression.html"><a href="binary-log-regression.html#activity-1-answers-3"><i class="fa fa-check"></i><b>5.4.3</b> Activity 1: Answers</a></li>
<li class="chapter" data-level="5.4.4" data-path="binary-log-regression.html"><a href="binary-log-regression.html#activity-2-answers-3"><i class="fa fa-check"></i><b>5.4.4</b> Activity 2: Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html"><i class="fa fa-check"></i><b>6</b> Lecture 9 (Extending binary logistic regression)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#lecture-4"><i class="fa fa-check"></i><b>6.1</b> Lecture</a></li>
<li class="chapter" data-level="6.2" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#pre-lab-work-4"><i class="fa fa-check"></i><b>6.2</b> Pre-lab work</a></li>
<li class="chapter" data-level="6.3" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#lab-4"><i class="fa fa-check"></i><b>6.3</b> Lab</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#model-script-3"><i class="fa fa-check"></i><b>6.3.1</b> Model script</a></li>
<li class="chapter" data-level="6.3.2" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#feedback-on-scripts-3"><i class="fa fa-check"></i><b>6.3.2</b> Feedback on scripts</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#independent-learning-4"><i class="fa fa-check"></i><b>6.4</b> Independent learning</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#activity-1-4"><i class="fa fa-check"></i><b>6.4.1</b> Activity 1</a></li>
<li class="chapter" data-level="6.4.2" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#activity-2-4"><i class="fa fa-check"></i><b>6.4.2</b> Activity 2</a></li>
<li class="chapter" data-level="6.4.3" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#activity-1-answers-4"><i class="fa fa-check"></i><b>6.4.3</b> Activity 1: Answers</a></li>
<li class="chapter" data-level="6.4.4" data-path="extending-binary-regression.html"><a href="extending-binary-regression.html#activity-2-answers-4"><i class="fa fa-check"></i><b>6.4.4</b> Activity 2: Answers</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC234 (Weeks 15-19)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="wilcoxon-rank-sum-signed-rank" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Lecture 6 (Non-parametric tests: Wilcoxon rank-sum and Wilcoxon signed-rank tests)<a href="wilcoxon-rank-sum-signed-rank.html#wilcoxon-rank-sum-signed-rank" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="lecture-1" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Lecture<a href="wilcoxon-rank-sum-signed-rank.html#lecture-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This lecture comprises four parts:</p>
<p><strong>Part 1: An introduction to non-parametric tests</strong></p>
<p>Part 1 covers an introduction to non-parametric tests and when they might be useful to consider. The lecture recording is available <a href="https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=fb98a72c-5f74-4fc7-bc51-ae3d01751e29">here</a> and the slides are available <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785786">here</a>.</p>
<p><strong>Part 2: Testing the assumption of normality with two independent groups</strong></p>
<p>Part 2 covers how to test the assumption of normality with two independent groups. The lecture recording is available <a href="https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=31ce4852-0c15-42b2-ab69-ae3d01800ef4">here</a> and the slides are available <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785786">here</a>.</p>
<p><strong>Part 3: The Wilcoxon-rank sum test</strong></p>
<p>Part 3 introduces you to the Wilcoxon rank-sum test. This includes when to use this test, the theory behind it, how the test statistic would be calculated manually, how to run the test in R, and how to interpret the output. The lecture recording is available <a href="https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=0affadb4-8523-4841-b467-ae3d0182426a">here</a> and the slides are available <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785786">here</a>.</p>
<p><strong>Part 4: The Wilcoxon signed-rank test</strong></p>
<p>Part 4 covers how to test the assumption of normality with two repeated measures and also introduces you to the Wilcoxon signed-rank test, including when to use the test, the theory behind it, how to calculate the test statistic manually, how to run the test in R and how to interpret the output. The lecture recording is available <a href="https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=3b79c12a-7482-44dc-b513-ae3d017a7bc7">here</a> and the slides are available <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785786">here</a>.</p>
</div>
<div id="pre-lab-work-1" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Pre-lab work<a href="wilcoxon-rank-sum-signed-rank.html#pre-lab-work-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before the lab, please watch the following <a href="https://dtu-panopto.lancs.ac.uk/Panopto/Pages/Viewer.aspx?id=0d934880-0288-4be1-a797-ae3c00f4ecf7">video</a>. This walks you through how to perform a Wilcoxon rank-sum test and Wilcoxon signed-rank test in R. The R markdown script covered in this video and the required data files can be downloaded <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1791571">here</a>.</p>
</div>
<div id="lab-1" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Lab<a href="wilcoxon-rank-sum-signed-rank.html#lab-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the lab, we’ll practice running a Wilcoxon rank-sum and Wilcoxon signed-rank test in R. Please download the following zip file which contains two datasets: <a href="files/Week_16/apple_study_data.csv">apple_study_data.csv</a> and <a href="files/Week_16/banana_study_data.csv">banana_study_data.csv</a>.</p>
<p>The datasets relate to the following research questions:</p>
<p><strong>1. Apple dataset</strong></p>
<p>You are a researcher interested in whether the old saying “an apple a day keeps the doctor away is true”. You recruit 16 people and assign each participant to either a “0 apples” or “1 apple” condition. Participants in the “0 apple” condition eat 0 apples every day for a year. Participants in the “1 apple” condition eat 1 apple a day for a year. You ask participants to report how many times they visited the GP in the year.</p>
<p><strong>2. Banana dataset</strong></p>
<p>You are interested in whether eating bananas keeps the doctor away.</p>
<p>This time you recruit only one group of participants. In the first year, you ask them to eat 0 banana every day. In the second year, you ask them to eat 1 bananas a day. You ask them to report how many times they visit the GP in Year 1 and Year 2.</p>
<p>Consider each research question, perform the normality checks, and then the appropriate analyses.</p>
<div id="model-script" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Model script<a href="wilcoxon-rank-sum-signed-rank.html#model-script" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here is a <a href="files/Week_16/Week_16_Lab_Model_Script.Rmd">model script</a> that produces the answers to the above research questions. I use the word ‘model’ loosely, as you may have used different functions you’ve learned over the last two years (and that’s absolutely fine!). So don’t worry if you haven’t used the exact same functions as me. You should end up with the same results and interpretation at the end though.</p>
</div>
<div id="feedback-on-scripts" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Feedback on scripts<a href="wilcoxon-rank-sum-signed-rank.html#feedback-on-scripts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Feedback on R scripts submitted by students is available <a href="https://modules.lancaster.ac.uk/mod/folder/view.php?id=1785808">here</a>.</p>
</div>
</div>
<div id="independent-learning-1" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Independent learning<a href="wilcoxon-rank-sum-signed-rank.html#independent-learning-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This is optional, but recommended. The answers are found below.</p>
<div id="activity-1-1" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Activity 1<a href="wilcoxon-rank-sum-signed-rank.html#activity-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Calculating test statistics manually</strong></p>
<div id="wilcoxon-rank-sum-test" class="section level4 hasAnchor" number="3.4.1.1">
<h4><span class="header-section-number">3.4.1.1</span> Wilcoxon rank-sum test<a href="wilcoxon-rank-sum-signed-rank.html#wilcoxon-rank-sum-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You are a researcher interested in whether the number of cups of coffee drank affects how many admin tasks participants can get done in an hour. You assign to one of two conditions (drink 4 cups of coffee a day or drink 0 cups of coffee a day). After a week, you ask participants to come into the lab and ask them to complete a range of admin tasks. You count how many admin tasks they manage to complete. The data are below.</p>
<p>Use this data to calculate the test statistic manually:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Group
</th>
<th style="text-align:center;">
Tasks_completed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
14
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
17
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
14
</td>
</tr>
</tbody>
</table>
<p>Steps:</p>
<ol style="list-style-type: decimal">
<li><p>First rank the data</p></li>
<li><p>Sum the ranks for each group</p></li>
<li><p>Calculate the mean rank for each group</p></li>
<li><p>Calculate the sum of ranks minus mean rank for each group</p></li>
<li><p>What is the test statistic?</p></li>
<li><p>What might R report as the test statistic and why?</p></li>
</ol>
</div>
<div id="wilcoxon-signed-rank-test" class="section level4 hasAnchor" number="3.4.1.2">
<h4><span class="header-section-number">3.4.1.2</span> Wilcoxon signed-rank test<a href="wilcoxon-rank-sum-signed-rank.html#wilcoxon-signed-rank-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You are a researcher interested in whether a reading intervention helps children. You assess children’s reading skills and then give them all an intensive reading intervention. You then measure their reading abilities again.</p>
<p>Use this data to calculate the test statistic manually</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Before_intervention
</th>
<th style="text-align:center;">
After_intervention
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
27
</td>
</tr>
<tr>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
34
</td>
</tr>
<tr>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;">
91
</td>
</tr>
<tr>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
67
</td>
</tr>
<tr>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
44
</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li><p>Calculate the difference between “Before intervention” and “After intervention”</p></li>
<li><p>Note whether the difference is positive or negative</p></li>
<li><p>Rank the difference</p></li>
<li><ol start="4" style="list-style-type: decimal">
<li>Next, add up positive ranks and negative ranks</li>
</ol></li>
<li><p>What is the test statistic (T)?</p></li>
<li><p>R reports a test statistic “<em>V</em>” instead of R. What might <em>V</em> equal to? Why might <em>V</em> equal to two values?</p></li>
</ol>
</div>
</div>
<div id="activity-2-1" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Activity 2<a href="wilcoxon-rank-sum-signed-rank.html#activity-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Interpreting R output</strong></p>
<p>Interpret the following R output. Part 1 uses an independent groups design. Part 2 uses a repeated measures design. Please note, this data are different to that used in Activity 1 (so the test statistics will be different).</p>
<div id="an-independent-groups-design" class="section level4 hasAnchor" number="3.4.2.1">
<h4><span class="header-section-number">3.4.2.1</span> An independent groups design<a href="wilcoxon-rank-sum-signed-rank.html#an-independent-groups-design" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="testing-the-assumption-of-normality" class="section level5 hasAnchor" number="3.4.2.1.1">
<h5><span class="header-section-number">3.4.2.1.1</span> Testing the assumption of normality<a href="wilcoxon-rank-sum-signed-rank.html#testing-the-assumption-of-normality" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div id="group-1" class="section level6 hasAnchor" number="3.4.2.1.1.1">
<h6><span class="header-section-number">3.4.2.1.1.1</span> Group 1:<a href="wilcoxon-rank-sum-signed-rank.html#group-1" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  group1$Outcome
## W = 0.72773, p-value = 0.01196</code></pre>
</div>
<div id="group-2" class="section level6 hasAnchor" number="3.4.2.1.1.2">
<h6><span class="header-section-number">3.4.2.1.1.2</span> Group 2:<a href="wilcoxon-rank-sum-signed-rank.html#group-2" class="anchor-section" aria-label="Anchor link to header"></a></h6>
<p><img src="_main_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  group2$Outcome
## W = 0.95764, p-value = 0.8014</code></pre>
<p>Is the assumption violated?</p>
</div>
</div>
<div id="interpret-the-descriptive-statistics-and-the-model-output" class="section level5 hasAnchor" number="3.4.2.1.2">
<h5><span class="header-section-number">3.4.2.1.2</span> Interpret the descriptive statistics and the model output<a href="wilcoxon-rank-sum-signed-rank.html#interpret-the-descriptive-statistics-and-the-model-output" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<pre><code>## Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Outcome by Group
## W = 19, p-value = 0.9357
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<pre><code>## # A tibble: 2 × 5
##   Group   med   min   max `n()`
##   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1     1  17       1    35     6
## 2     2   5.5     2     9     6</code></pre>
<p>What can we conclude? Report in APA format.</p>
<p>How was the p-value calculated?</p>
</div>
</div>
<div id="a-repeated-measures-design" class="section level4 hasAnchor" number="3.4.2.2">
<h4><span class="header-section-number">3.4.2.2</span> A repeated measures design<a href="wilcoxon-rank-sum-signed-rank.html#a-repeated-measures-design" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You are a researcher interested in whether the amount of chocolate eaten is different before and after the participant goes a diet.</p>
<div id="testing-the-assumption-of-normality-1" class="section level5 hasAnchor" number="3.4.2.2.1">
<h5><span class="header-section-number">3.4.2.2.1</span> Testing the assumption of normality<a href="wilcoxon-rank-sum-signed-rank.html#testing-the-assumption-of-normality-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  worksheet_activity2$Difference
## W = 0.76888, p-value = 0.01318</code></pre>
<p>Is the assumption violated?</p>
</div>
<div id="interpret-the-descriptive-statistics-and-the-model-output-1" class="section level5 hasAnchor" number="3.4.2.2.2">
<h5><span class="header-section-number">3.4.2.2.2</span> Interpret the descriptive statistics and the model output<a href="wilcoxon-rank-sum-signed-rank.html#interpret-the-descriptive-statistics-and-the-model-output-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<pre><code>## Warning in wilcox.test.default(worksheet_activity2$Before, worksheet_activity2$After, : cannot compute exact p-value with
## ties</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  worksheet_activity2$Before and worksheet_activity2$After
## V = 36, p-value = 0.01368
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<pre><code>##   median_before median_after min_before min_after max_before max_after n()
## 1           232           18        230         4        235        33   8</code></pre>
<p>What can we conclude? Report in APA format.</p>
<p>How was the p-value calculated?</p>
</div>
</div>
</div>
<div id="activity-1-answers-1" class="section level3 hasAnchor" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Activity 1: Answers<a href="wilcoxon-rank-sum-signed-rank.html#activity-1-answers-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="wilcoxon-rank-sum-test-1" class="section level4 hasAnchor" number="3.4.3.1">
<h4><span class="header-section-number">3.4.3.1</span> Wilcoxon rank-sum test<a href="wilcoxon-rank-sum-signed-rank.html#wilcoxon-rank-sum-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Steps:</p>
<p><strong>1. First rank the data</strong></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Group
</th>
<th style="text-align:center;">
Tasks_completed
</th>
<th style="text-align:center;">
Rank
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2.0
</td>
</tr>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
7.0
</td>
</tr>
<tr>
<td style="text-align:center;">
4 cups
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
4.5
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
3.0
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1.0
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
6.0
</td>
</tr>
<tr>
<td style="text-align:center;">
0 cups
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
4.5
</td>
</tr>
</tbody>
</table>
<p><strong>2. Sum the ranks per group</strong></p>
<p><span style="color:purple">4 cups = 13.5</span></p>
<p><span style="color:purple">0 cups = 14.5</span></p>
<p><strong>3. Calculate the mean rank per group</strong></p>
<p><span style="color:purple">4 cups = 3*4 = 12. 12/2 = 6</span></p>
<p><span style="color:purple">0 cups = 4*5 = 20. 20/2 = 10</span></p>
<p><strong>4. Calculate the sum of ranks minus mean rank per group</strong></p>
<p><span style="color:purple">4 cups = 13.5-6 = 7.5</span></p>
<p><span style="color:purple">0 cups = 14.5-10 = 4.5</span></p>
<p><strong>5. What is the test statistic?</strong></p>
<p><span style="color:purple">Test statistic = The lowest sum of ranks. Test statistic = 4.5</span></p>
<p><strong>6. What might R report as the test statistic and why?</strong></p>
<p><span style="color:purple">R reports the test statistic (<em>W</em>) as the sum of ranks minus the mean rank for the first factor level. R may therefore report the test statistic as 4.5 or 7.5.</span></p>
</div>
<div id="wilcoxon-signed-rank-test-1" class="section level4 hasAnchor" number="3.4.3.2">
<h4><span class="header-section-number">3.4.3.2</span> Wilcoxon signed-rank test<a href="wilcoxon-rank-sum-signed-rank.html#wilcoxon-signed-rank-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><strong>1. Calculate the difference between “Before intervention” and “After intervention”</strong></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Before_intervention
</th>
<th style="text-align:center;">
After_intervention
</th>
<th style="text-align:center;">
Difference
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;color: purple !important;">
-4
</td>
</tr>
<tr>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;color: purple !important;">
Exclude
</td>
</tr>
<tr>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;">
91
</td>
<td style="text-align:center;color: purple !important;">
-24
</td>
</tr>
<tr>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;color: purple !important;">
-2
</td>
</tr>
<tr>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
44
</td>
<td style="text-align:center;color: purple !important;">
-23
</td>
</tr>
</tbody>
</table>
<p><strong>2. Note whether the difference is positive or negative</strong></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Before_intervention
</th>
<th style="text-align:center;">
After_intervention
</th>
<th style="text-align:center;">
Difference
</th>
<th style="text-align:center;">
Sign
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;color: purple !important;">
-4
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
</tr>
<tr>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;color: purple !important;">
Exclude
</td>
<td style="text-align:center;color: purple !important;">
</td>
</tr>
<tr>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;">
91
</td>
<td style="text-align:center;color: purple !important;">
-24
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
</tr>
<tr>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;color: purple !important;">
-2
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
</tr>
<tr>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
44
</td>
<td style="text-align:center;color: purple !important;">
-23
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
</tr>
</tbody>
</table>
<p><strong>3. Rank the difference</strong></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Before_intervention
</th>
<th style="text-align:center;">
After_intervention
</th>
<th style="text-align:center;">
Difference
</th>
<th style="text-align:center;">
Sign
</th>
<th style="text-align:center;">
Rank
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
27
</td>
<td style="text-align:center;color: purple !important;">
-4
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
<td style="text-align:center;color: purple !important;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;color: purple !important;">
Exclude
</td>
<td style="text-align:center;color: purple !important;">
</td>
<td style="text-align:center;color: purple !important;">
</td>
</tr>
<tr>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;">
91
</td>
<td style="text-align:center;color: purple !important;">
-24
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
<td style="text-align:center;color: purple !important;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
65
</td>
<td style="text-align:center;">
67
</td>
<td style="text-align:center;color: purple !important;">
-2
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
<td style="text-align:center;color: purple !important;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
44
</td>
<td style="text-align:center;color: purple !important;">
-23
</td>
<td style="text-align:center;color: purple !important;">
Negative
</td>
<td style="text-align:center;color: purple !important;">
3
</td>
</tr>
</tbody>
</table>
<p><strong>4. Next, add up positive ranks and negative ranks</strong></p>
<p><span style="color:purple">Positive ranks: 0</span></p>
<p><span style="color:purple">Negative ranks: 10</span></p>
<p><strong>5. What is the test statistic (<em>T</em>)?</strong></p>
<p><span style="color:purple"><em>T</em> = 0</span></p>
<p><strong>6. R reports a test statistic “<em>V</em>” instead of R. What might <em>V</em> equal to? Why might <em>V</em> equal to two values?</strong></p>
<p><span style="color:purple"><em>V</em> = 0 or 10. <em>V</em> is equal to the sum of positive ranks. But whether ranks are positive or negative depends on whether you enter “before” or “after” first into the wilcox.test function (as this determines whether you calculate the difference by doing before-after or after-before).</span></p>
</div>
</div>
<div id="activity-2-answers-1" class="section level3 hasAnchor" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> Activity 2: Answers<a href="wilcoxon-rank-sum-signed-rank.html#activity-2-answers-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="an-independent-groups-design-1" class="section level4 hasAnchor" number="3.4.4.1">
<h4><span class="header-section-number">3.4.4.1</span> An independent groups design:<a href="wilcoxon-rank-sum-signed-rank.html#an-independent-groups-design-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="testing-the-assumption-of-normality-2" class="section level4 hasAnchor" number="3.4.4.2">
<h4><span class="header-section-number">3.4.4.2</span> Testing the assumption of normality<a href="wilcoxon-rank-sum-signed-rank.html#testing-the-assumption-of-normality-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="group-1-1" class="section level5 hasAnchor" number="3.4.4.2.1">
<h5><span class="header-section-number">3.4.4.2.1</span> Group 1:<a href="wilcoxon-rank-sum-signed-rank.html#group-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  group1$Outcome
## W = 0.72773, p-value = 0.01196</code></pre>
</div>
<div id="group-2-1" class="section level5 hasAnchor" number="3.4.4.2.2">
<h5><span class="header-section-number">3.4.4.2.2</span> Group 2:<a href="wilcoxon-rank-sum-signed-rank.html#group-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  group2$Outcome
## W = 0.95764, p-value = 0.8014</code></pre>
<p><strong>Is the assumption violated?</strong></p>
<p><span style="color:purple">Group 1: The assumption of normality is violated. Quite a few points deviate from the line in the Q-Q plot and the Shapiro-Wilk test is significant.</span></p>
<p><span style="color:purple">Group 2: The assumption of normality is not violated. The dots generally follow the line well in the Q-Q plot and the Shapiro-Wilk test is non-significant.</span></p>
</div>
</div>
<div id="interpret-the-descriptive-statistics-and-the-model-output-2" class="section level4 hasAnchor" number="3.4.4.3">
<h4><span class="header-section-number">3.4.4.3</span> Interpret the descriptive statistics and the model output<a href="wilcoxon-rank-sum-signed-rank.html#interpret-the-descriptive-statistics-and-the-model-output-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Outcome by Group
## W = 19, p-value = 0.9357
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<pre><code>## # A tibble: 2 × 5
##   Group   med   min   max `n()`
##   &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1     1  17       1    35     6
## 2     2   5.5     2     9     6</code></pre>
<p><strong>What can we conclude? Report in APA format.</strong></p>
<p><span style="color:purple">The Wilcoxon rank-sum test revealed no significant difference between Group 1 (Median = 17, Range = 1-35) and Group 2 (Median = 5.5, Range = 2-9; <em>W</em> = 19, <em>p</em> = 0.936).</span></p>
<p><span style="color:purple">Note: In practice, you should also calculate the effect size and report that.</span></p>
<p><strong>How was the p-value calculated?</strong></p>
<p><span style="color:purple">The normal approximation with the continuity correction</span></p>
</div>
<div id="a-repeated-measures-design-1" class="section level4 hasAnchor" number="3.4.4.4">
<h4><span class="header-section-number">3.4.4.4</span> A repeated measures design<a href="wilcoxon-rank-sum-signed-rank.html#a-repeated-measures-design-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="testing-the-assumption-of-normality-3" class="section level4 hasAnchor" number="3.4.4.5">
<h4><span class="header-section-number">3.4.4.5</span> Testing the assumption of normality<a href="wilcoxon-rank-sum-signed-rank.html#testing-the-assumption-of-normality-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  worksheet_activity2$Difference
## W = 0.76888, p-value = 0.01318</code></pre>
<p><strong>Is the assumption violated?</strong></p>
<p><span style="color:purple">The assumption of normality is violated. Some points deviate quite a bit from the line in the Q-Q plot and the Shapiro-Wilk test is significant.</span></p>
</div>
<div id="interpret-the-descriptive-statistics-and-the-model-output-3" class="section level4 hasAnchor" number="3.4.4.6">
<h4><span class="header-section-number">3.4.4.6</span> Interpret the descriptive statistics and the model output<a href="wilcoxon-rank-sum-signed-rank.html#interpret-the-descriptive-statistics-and-the-model-output-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  worksheet_activity2$Before and worksheet_activity2$After
## V = 36, p-value = 0.01368
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<pre><code>##   median_before median_after min_before min_after max_before max_after n()
## 1           232           18        230         4        235        33   8</code></pre>
<p><strong>What can we conclude? Report in APA format.</strong></p>
<p><span style="color:purple">The Wilcoxon signed-rank test revealed that participants ate significantly more grams of chocolate before the diet (Median = 232, Range = 230-235) than after the diet (Median = 18; Range = 4-33), <em>V</em> = 36, <em>p</em> = 0.014.</span></p>
<p><span style="color:purple">Note: In practice, you should also calculate the effect size and report that.</span></p>
<p><strong>How was the p-value calculated?</strong></p>
<p><span style="color:purple">The normal approximation with the continuity correction</span></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="binomial_test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="kruskal-friedman.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
